export const LoaderConfig = {
    background: require("../sprites/Background.png"),
    cover: require("../sprites/cover.png"),
    bgFx1 : require("../sprites/bgFx.png"),
    board1 : require("../sprites/Board1.png"),
    pawn1 : require("../sprites/pawnYellow.png"),
    pawn2 : require("../sprites/pawnBlue.png"),
    pawn3 : require("../sprites/pawnRed.png"),
    pawn4 : require("../sprites/pawnGreen.png"),
    diceBG : require("../sprites/diceBG.png"),
    avatar : require("../sprites/Avatar.png"),
    dice1 : require("../sprites/dice1.png"),
    dice2 : require("../sprites/dice2.png"),
    dice3 : require("../sprites/dice3.png"),
    dice4 : require("../sprites/dice4.png"),
    dice5 : require("../sprites/dice5.png"),
    dice6 : require("../sprites/dice6.png"),
    diceEdge1 : require("../sprites/diceEdge1.png"),
    diceEdge2 : require("../sprites/diceEdge2.png"),
    diceEdge3 : require("../sprites/diceEdge3.png"),
    diceEdge4 : require("../sprites/diceEdge4.png"),
    diceEdge5 : require("../sprites/diceEdge5.png"),
    diceEdge6 : require("../sprites/diceEdge6.png"),
    logo : require("../sprites/Logo.png"),
    playBtn : require("../sprites/PlayBtn.png"),


    click : require("../sounds/click.mp3"),
    dice :  require("../sounds/dice-5.mp3")
};